name: AWS Deployment

on:
  pull_request:
    branches: 
      - main
    types: [closed]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          #aws-region: <change_region>

      - name: Sync files to S3
        # run: |
          # aws s3 sync . s3://<change_bucket_name> --delete
