services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: tennis-backend:local
    pull_policy: build

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: tennis-frontend:local
    pull_policy: build
