ALTER TABLE users ADD COLUMN IF NOT EXISTS terms_conditions_accepted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS terms_conditions_accepted_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS terms_conditions_version VARCHAR(20);
