-- Database Schema for Tennis Tournament Platform (H2 Compatible)

DROP TABLE IF EXISTS rankings;
DROP TABLE IF EXISTS sets;
DROP TABLE IF EXISTS matchup_sides;
DROP TABLE IF EXISTS matchups;
DROP TABLE IF EXISTS draws;
DROP TABLE IF EXISTS stages;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS ref_age_category;
DROP TABLE IF EXISTS tournament_categories;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS participant_persons;
DROP TABLE IF EXISTS participants;
DROP TABLE IF EXISTS inscriptions;
DROP TABLE IF EXISTS tournaments;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS persons;

CREATE TABLE persons (
    id            UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    tennis_id     VARCHAR(50) UNIQUE,
    first_name    VARCHAR(100) NOT NULL,
    last_name     VARCHAR(100),
    nationality   CHAR(3),
    birth_date    DATE,
    gender        VARCHAR(20)
);

CREATE TABLE users (
    id            UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    email         VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    token_hash    VARCHAR(128),
    tier          VARCHAR(20) DEFAULT 'FREE',
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    person_id     UUID,
    FOREIGN KEY (person_id) REFERENCES persons(id)
);

CREATE TABLE categories (
    id      UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    name    VARCHAR(255),
    genre   VARCHAR(1),
    mode    VARCHAR(20)
);

CREATE TABLE tournaments (
    id                      UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    name                    VARCHAR(255) NOT NULL,
    start_date              DATE NOT NULL,
    end_date                DATE NOT NULL,
    inscription_start_date  DATE,
    inscription_end_date    DATE,
    surface                 VARCHAR(20),
    max_players             INTEGER,
    location                VARCHAR(255),
    state                   VARCHAR(20) DEFAULT 'DRAFT',
    created_by              UUID,
    venue                   VARCHAR(255),
    country                 CHAR(3),
    category                VARCHAR(50),
    FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE tournament_categories (
    tournament_id   UUID NOT NULL,
    category_id     UUID NOT NULL,
    PRIMARY KEY (tournament_id, category_id),
    FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE participants (
    id               UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    tournament_id    UUID NOT NULL,
    person_id        UUID,
    participant_type VARCHAR(20) NOT NULL,
    entry_status     VARCHAR(30),
    seed             INTEGER,
    FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    FOREIGN KEY (person_id) REFERENCES persons(id)
);

CREATE TABLE participant_persons (
    participant_id  UUID NOT NULL,
    person_id       UUID NOT NULL,
    PRIMARY KEY (participant_id, person_id),
    FOREIGN KEY (participant_id) REFERENCES participants(id),
    FOREIGN KEY (person_id) REFERENCES persons(id)
);

CREATE TABLE ref_age_category (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category    VARCHAR(20) NOT NULL,
    description VARCHAR(20)
);

CREATE TABLE events (
    id              UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    tournament_id   UUID NOT NULL,
    age_category_id INTEGER,
    name            VARCHAR(255),
    discipline      VARCHAR(50),
    event_type      VARCHAR(20),
    gender          VARCHAR(20),
    draw_size       INTEGER,
    FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    FOREIGN KEY (age_category_id) REFERENCES ref_age_category(id)
);

CREATE TABLE inscriptions (
    id              UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    event_id        UUID NOT NULL,
    participant_id  UUID NOT NULL,
    status          VARCHAR(20) DEFAULT 'PENDING',
    payment_status  VARCHAR(20) DEFAULT 'UNPAID',
    registered_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    FOREIGN KEY (participant_id) REFERENCES participants(id) ON DELETE CASCADE,
    UNIQUE (event_id, participant_id)
);

CREATE INDEX idx_inscriptions_event ON inscriptions(event_id);
CREATE INDEX idx_inscriptions_participant ON inscriptions(participant_id);

CREATE TABLE stages (
    id              UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    event_id        UUID NOT NULL,
    stage_number    INTEGER NOT NULL,
    stage_type      VARCHAR(30),
    FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE draws (
    id              UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    stage_id        UUID NOT NULL,
    draw_type       VARCHAR(30) NOT NULL,
    draw_name       VARCHAR(100),
    FOREIGN KEY (stage_id) REFERENCES stages(id)
);

CREATE TABLE matchups (
    id              UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    draw_id         UUID NOT NULL,
    round_number    INTEGER,
    match_number    INTEGER,
    match_format    VARCHAR(100),
    status          VARCHAR(20),
    scheduled_at    TIMESTAMP,
    court           VARCHAR(100),
    winner_side     SMALLINT,
    FOREIGN KEY (draw_id) REFERENCES draws(id)
);

CREATE TABLE matchup_sides (
    id              UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    matchup_id      UUID NOT NULL,
    side_number     SMALLINT NOT NULL,
    participant_id  UUID,
    UNIQUE (matchup_id, side_number),
    FOREIGN KEY (matchup_id) REFERENCES matchups(id),
    FOREIGN KEY (participant_id) REFERENCES participants(id)
);

CREATE TABLE sets (
    id              UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    matchup_id      UUID NOT NULL,
    set_number      SMALLINT NOT NULL,
    side1_games     SMALLINT,
    side2_games     SMALLINT,
    side1_tiebreak  SMALLINT,
    side2_tiebreak  SMALLINT,
    UNIQUE (matchup_id, set_number),
    FOREIGN KEY (matchup_id) REFERENCES matchups(id)
);

CREATE TABLE rankings (
    id              UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    person_id       UUID NOT NULL,
    ranking_date    DATE NOT NULL,
    ranking_type    VARCHAR(50),
    rank_position   INTEGER,
    ranking_points  NUMERIC(10,2),
    UNIQUE (person_id, ranking_date, ranking_type),
    FOREIGN KEY (person_id) REFERENCES persons(id)
);