-- Database Schema for Tennis Tournament Platform (H2 Compatible)

DROP TABLE IF EXISTS consent_records;
DROP TABLE IF EXISTS legal_document_versions;
DROP TABLE IF EXISTS pro_player_imports;
DROP TABLE IF EXISTS pro_players;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS draws;
DROP TABLE IF EXISTS stages;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS ref_age_category;
DROP TABLE IF EXISTS participant_persons;
DROP TABLE IF EXISTS participants;
DROP TABLE IF EXISTS inscriptions;
DROP TABLE IF EXISTS tournaments;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS persons;

CREATE TABLE persons (
    id            UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    tennis_id     VARCHAR(50) UNIQUE,
    first_name    VARCHAR(100) NOT NULL,
    last_name     VARCHAR(100),
    nationality   CHAR(3),
    birth_date    DATE,
    gender        VARCHAR(20)
);

CREATE TABLE users (
    id            UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    email         VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    token_hash    VARCHAR(128),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    email_confirmation_token_hash VARCHAR(128),
    email_confirmation_expires_at TIMESTAMP,
    tier          VARCHAR(20) DEFAULT 'FREE',
    user_role     VARCHAR(20) DEFAULT 'PLAYER',
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    privacy_policy_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    privacy_policy_accepted_at TIMESTAMP,
    privacy_policy_version VARCHAR(20),
    terms_conditions_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    terms_conditions_accepted_at TIMESTAMP,
    terms_conditions_version VARCHAR(20),
    person_id     UUID,
    FOREIGN KEY (person_id) REFERENCES persons(id)
);

CREATE TABLE legal_document_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR(20) NOT NULL,
    version VARCHAR(20) NOT NULL,
    content_snapshot CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_legal_document_version UNIQUE (document_type, version)
);

CREATE TABLE consent_records (
    id UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    user_id UUID NOT NULL,
    document_type VARCHAR(20) NOT NULL,
    action VARCHAR(10) NOT NULL,
    document_version_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (document_version_id) REFERENCES legal_document_versions(id)
);

CREATE INDEX idx_consent_records_user_id ON consent_records(user_id);
CREATE INDEX idx_consent_records_user_doc ON consent_records(user_id, document_type);

CREATE TABLE tournaments (
    id                      UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    name                    VARCHAR(255) NOT NULL,
    start_date              DATE NOT NULL,
    end_date                DATE NOT NULL,
    start_time              TIME,
    inscription_start_date  DATE,
    inscription_end_date    DATE,
    surface                 VARCHAR(20),
    max_players             INTEGER,
    location                VARCHAR(255),
    location_latitude       DOUBLE PRECISION,
    location_longitude      DOUBLE PRECISION,
    location_place_id       VARCHAR(255),
    location_formatted_address VARCHAR(500),
    state                   VARCHAR(20) DEFAULT 'DRAFT',
    version                 BIGINT NOT NULL DEFAULT 0,
    created_by              UUID,
    venue                   VARCHAR(255),
    country                 CHAR(3),
    category                VARCHAR(50),
    FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE participants (
    id               UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    tournament_id    UUID NOT NULL,
    person_id        UUID,
    participant_source VARCHAR(30),
    display_first_name VARCHAR(100),
    display_last_name VARCHAR(100),
    display_gender   VARCHAR(20),
    display_birth_date DATE,
    display_nationality VARCHAR(50),
    display_tennis_id VARCHAR(50),
    participant_type VARCHAR(20) NOT NULL,
    entry_status     VARCHAR(30),
    seed             INTEGER,
    FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    FOREIGN KEY (person_id) REFERENCES persons(id)
);

CREATE TABLE participant_persons (
    participant_id  UUID NOT NULL,
    person_id       UUID NOT NULL,
    PRIMARY KEY (participant_id, person_id),
    FOREIGN KEY (participant_id) REFERENCES participants(id),
    FOREIGN KEY (person_id) REFERENCES persons(id)
);

CREATE TABLE ref_age_category (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category    VARCHAR(20) NOT NULL,
    description VARCHAR(20),
    display_order INTEGER,
    organizer_id UUID NULL,
    FOREIGN KEY (organizer_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_ref_age_category_organizer ON ref_age_category(organizer_id);

CREATE TABLE events (
    id              UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    tournament_id   UUID NOT NULL,
    age_category_id INTEGER,
    name            VARCHAR(255),
    discipline      VARCHAR(50),
    event_type      VARCHAR(20),
    gender          VARCHAR(20),
    draw_size       INTEGER,
    FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    FOREIGN KEY (age_category_id) REFERENCES ref_age_category(id)
);

CREATE TABLE inscriptions (
    id              UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    event_id        UUID NOT NULL,
    participant_id  UUID NOT NULL,
    status          VARCHAR(20) DEFAULT 'PENDING',
    payment_status  VARCHAR(20) DEFAULT 'UNPAID',
    registered_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    FOREIGN KEY (participant_id) REFERENCES participants(id) ON DELETE CASCADE,
    UNIQUE (event_id, participant_id)
);

CREATE INDEX idx_inscriptions_event ON inscriptions(event_id);
CREATE INDEX idx_inscriptions_participant ON inscriptions(participant_id);

CREATE TABLE stages (
    id              UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    event_id        UUID NOT NULL,
    stage_order     INTEGER NOT NULL,
    stage_type      VARCHAR(30),
    strategy_name   VARCHAR(50),
    description     VARCHAR,
    FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE draws (
    id              UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    stage_id        UUID NOT NULL,
    draw_type       VARCHAR(30) NOT NULL,
    label           VARCHAR(100),
    FOREIGN KEY (stage_id) REFERENCES stages(id)
);

COMMENT ON COLUMN draws.label IS 'Draw visible name';

CREATE TABLE courts (
    id              UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    tournament_id   UUID NOT NULL,
    name            VARCHAR(100) NOT NULL,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE,
    UNIQUE (tournament_id, name)
);

CREATE TABLE matches (
    id                      UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    draw_id                 UUID NOT NULL,
    first_inscription_id    UUID,
    second_inscription_id   UUID,
    winner_id               UUID,
    round_number            INTEGER,
    bracket_position        INTEGER,
    next_match_id           UUID,
    loser_next_match_id     UUID,
    scheduled_at            TIMESTAMP,
    schedule_type           VARCHAR(20),
    court_id                UUID,
    court                   VARCHAR(100),
    result                  VARCHAR(255),
    version                 BIGINT NOT NULL DEFAULT 0,
    FOREIGN KEY (draw_id) REFERENCES draws(id),
    FOREIGN KEY (first_inscription_id) REFERENCES inscriptions(id),
    FOREIGN KEY (second_inscription_id) REFERENCES inscriptions(id),
    FOREIGN KEY (winner_id) REFERENCES inscriptions(id),
    FOREIGN KEY (next_match_id) REFERENCES matches(id),
    FOREIGN KEY (loser_next_match_id) REFERENCES matches(id),
    FOREIGN KEY (court_id) REFERENCES courts(id) ON DELETE SET NULL
);

CREATE TABLE pro_players (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    puntos INTEGER NOT NULL,
    licencia VARCHAR(20),
    name VARCHAR(255) NOT NULL,
    posicion INTEGER NOT NULL,
    posicion_territorial INTEGER NOT NULL,
    posicion_provincial INTEGER NOT NULL,
    posicion_club INTEGER NOT NULL,
    posicion_edad INTEGER NOT NULL,
    edad VARCHAR(50) NOT NULL,
    nombre_club VARCHAR(255) NOT NULL,
    nombre_provincial VARCHAR(255) NOT NULL,
    nombre_territorial VARCHAR(255) NOT NULL,
    nombre_categoria VARCHAR(255) NOT NULL,
    puntos_otorga INTEGER NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    gender VARCHAR(10) NOT NULL
);

CREATE INDEX idx_pro_players_gender_position ON pro_players(gender, posicion);
CREATE INDEX idx_pro_players_license ON pro_players(licencia);
CREATE INDEX idx_pro_players_name ON pro_players(name);

-- Performance indexes
CREATE INDEX idx_participants_person ON participants(person_id);
CREATE INDEX idx_events_age_category ON events(age_category_id);
CREATE INDEX idx_matches_court ON matches(court_id);
CREATE INDEX idx_matches_round ON matches(round_number);
CREATE INDEX idx_tournaments_state ON tournaments(state);
CREATE INDEX idx_tournaments_start_date ON tournaments(start_date);
CREATE INDEX idx_users_person ON users(person_id);
CREATE INDEX idx_users_user_role ON users(user_role);

CREATE TABLE pro_player_imports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name VARCHAR(100) NOT NULL,
    checksum VARCHAR(128) NOT NULL,
    row_count INTEGER NOT NULL,
    imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(30) NOT NULL,
    error_message CLOB
);

CREATE INDEX idx_pro_player_imports_source_checksum_status
ON pro_player_imports(source_name, checksum, status);
